version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: weekly
    day: 'friday'
    time: '17:00'
    timezone: 'America/Los_Angeles'
  open-pull-requests-limit: 10
  groups:
    coverlet:
      patterns:
      - "coverlet*"
    OpenTelemetry:
      patterns:
      - "OpenTelemetry*"
    xunit:
      patterns:
      - "xunit*"
    gitversioning:
      patterns:
      - "Nerdbank.GitVersioning"
      - "nbgv"

- package-ecosystem: 'dotnet-sdk'
  directory: "/"
  schedule:
    interval: 'weekly'
    day: 'tuesday'
    time: '20:00'
    timezone: 'America/Los_Angeles'
  open-pull-requests-limit: 10

- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
    day: 'friday'
    time: '17:00'
    timezone: 'America/Los_Angeles'
  open-pull-requests-limit: 10
