name: Check for image updates

inputs:
  image:
    type: string
    required: true
    description: The container image to verify against the base image.
  base-image:
    type: string
    required: true
    description: The container base image.
outputs:
  needs-updating:
    description: Whether the base image needs updating. Either `true` or `false`.
    value: ${{ steps.update-check.outputs.needsBaseUpdate }}

runs:
  using: "composite"
  steps:
    - name: Check base image
      id: update-check
      shell: pwsh
      run: |
        $imageNeedsUpdate = ${{ github.action_path }}/CheckImageNeedsBaseUpdate.ps1 -Image ${{ inputs.image }} -BaseImage ${{ inputs.base-image }} -CheckDateCreated
        Write-Host "needsBaseUpdate=$($imageNeedsUpdate.ToString().ToLower())"
        "needsBaseUpdate=$($imageNeedsUpdate.ToString().ToLower())" >> $env:GITHUB_OUTPUT
