name: 'SynologyDdnsUpdater-CI'

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.config/**'
      - '.github/dependabot.yml'
      - '.vscode/**'
      - 'docs/**'
      - 'README.md'

env:
  # Stop wasting time caching packages
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

jobs:
  build_pr:
    uses: ./.github/workflows/workflow_build.yml
    secrets: inherit
    with:
      # build on feature branches, push only on main branch
      push: ${{ github.ref == 'refs/heads/main' }}
      # don't check format on CI builds due to common breaking changes in the .NET SDK
      checkFormat: false

  deploy:
    name: 'Deploy SynologyDdnsUpdater'
    runs-on: ubuntu-latest
    needs: build_pr
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download webapp_package artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: webapp_package
          path: webapp_package

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ vars.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: webapp_package
