name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.config/**'
      - '.github/dependabot.yml'
      - '.vscode/**'
      - 'docs/**'
      - 'README.md'

jobs:
  build_ci:
    name: CI Build
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    uses: ./.github/workflows/workflow_build.yml
    secrets: inherit
    with:
      # build on feature branches, push only on main branch
      push: ${{ github.ref == 'refs/heads/main' }}
      # don't check format on CI builds due to common breaking changes in the .NET SDK
      checkFormat: false

  deploy_ci:
    name: Deploy app to Azure
    needs: build_ci
    uses: ./.github/workflows/workflow_deploy.yml
    secrets: inherit
