name: 'SynologyDdnsUpdater-PR'

on: pull_request

env:
  # Stop wasting time caching packages
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

jobs:
  build:
    name: 'Build SynologyDdnsUpdater'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.x

      - name: Install dependencies
        run: dotnet restore

      - name: DotNet Format
        run: dotnet format --no-restore --verify-no-changes

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --configuration Release --no-build --verbosity normal --collect:"XPlat Code Coverage"

      - name: Publish
        run: dotnet publish --configuration Release --no-build src/Synology.Ddns.Update.Service

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          name: codecov-${{ matrix.platform }}
          directory: __test-results
          fail_ci_if_error: true
          verbose: true

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Build container image
        uses: docker/build-push-action@v2
        with:
          file: src/Synology.Ddns.Update.Service/Dockerfile
          # relative path to the place where source code with Dockerfile is located
          context: __publish/Release/AnyCPU/src/Synology.Ddns.Update.Service/net7.0
          # build-time arguments
          build-args: |
            finalStage=fromlocal
          # Note: tags has to be all lower-case
          tags: |
            synologyddnsupdater:pr
          # Never push on PR builds
          push: false
