name: 'SynologyDdnsUpdater-PR'

on: pull_request

jobs:
  build_pr:
    name: SynologyDdnsUpdater PR Build
    uses: ./.github/workflows/workflow_build.yml
    secrets: inherit
    with:
      # Never push on PR builds
      push: false
