# A rolling build that periodically checks if there's a base container image update.
# If there is, we perform another official build and deploy it using the latest
# container image.
name: Rolling

on:
  schedule:
    - cron:  '35 9 * * *'

jobs:
  check:
    name: Rolling check
    runs-on: ubuntu-latest
    outputs:
      needs-updating: ${{ steps.update-check.outputs.needs-updating }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Container Image Update Check
        id: update-check
        uses: ./.github/actions/image-update-check
        with:
          base-image: mcr.microsoft.com/dotnet/aspnet:8.0-cbl-mariner2.0-distroless
          image: craigktreasure/synologyddnsupdater:latest

  build_rolling:
    name: Rolling Build
    needs: check
    if: needs.check.outputs.needs-updating == 'true'
    uses: ./.github/workflows/workflow_build.yml
    secrets: inherit
    with:
      # build on feature branches, push only on main branch
      push: ${{ github.ref == 'refs/heads/main' }}
      # don't check format on CI builds due to common breaking changes in the .NET SDK
      checkFormat: false
