name: Build SynologyDdnsUpdater

on:
  workflow_call:
    inputs:
      push:
        type: boolean
      checkFormat:
        type: boolean
        default: true
    outputs:
      package_version:
        description: 'The version of the package that was built.'
        value: ${{ jobs.build.outputs.package_version }}
      container_version:
        description: 'The version of the container that was built.'
        value: ${{ jobs.build.outputs.container_version }}

env:
  # Stop wasting time caching packages
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    outputs:
      package_version: ${{steps.version.outputs.package_version}}
      container_version: ${{steps.version.outputs.container_version}}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install tools
        uses: ./.github/actions/install-tools

      - name: Set version variables
        id: version
        uses: ./.github/actions/version-vars

      - name: Restore
        run: dotnet restore

      - name: Format validation
        if: ${{ inputs.checkFormat }}
        run: dotnet format --no-restore --verify-no-changes

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --configuration Release --no-build --verbosity normal /p:CollectCoverage=true

      - name: Publish
        run: dotnet publish --configuration Release --no-build

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          name: codecov
          directory: __artifacts/test-results
          fail_ci_if_error: true
          verbose: true

      - name: Upload publish artifact
        if: ${{ inputs.push }}
        uses: actions/upload-artifact@v3
        with:
          name: publish
          path: __artifacts/publish

      - name: Upload webapp_package artifact for deployment job
        if: ${{ inputs.push }}
        uses: actions/upload-artifact@v3
        with:
          name: webapp_package
          path: __artifacts/publish/Synology.Ddns.Update.Service/release

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        if: ${{ inputs.push }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          logout: true

      # https://github.com/docker/build-push-action
      - name: Build container image
        if: ${{ !inputs.push }}
        uses: docker/build-push-action@v5
        with:
          file: src/Synology.Ddns.Update.Service/Dockerfile
          # relative path to published binary location
          context: __artifacts/publish/Synology.Ddns.Update.Service/release
          # build-time arguments
          build-args: |
            finalStage=fromlocal
          # Note: tags has to be all lower-case
          tags: |
            synologyddnsupdater_pr:${{ env.container_version }}
          push: false

      # https://github.com/docker/build-push-action
      - name: Build and push container image
        if: ${{ inputs.push }}
        uses: docker/build-push-action@v5
        with:
          file: src/Synology.Ddns.Update.Service/Dockerfile
          # relative path to published binary location
          context: __artifacts/publish/Synology.Ddns.Update.Service/release
          # build-time arguments
          build-args: |
            finalStage=fromlocal
          # Note: tags has to be all lower-case
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/synologyddnsupdater:${{ env.container_version }}
            ${{ secrets.DOCKERHUB_USERNAME }}/synologyddnsupdater:latest
          # build on feature branches, push only on main branch
          push: ${{ github.ref == 'refs/heads/main' }}
